name: Build and Push Docker Image

on:
  schedule:
    - cron: '0 0 * * *'   # Daily at midnight UTC (adjust as needed)
  workflow_dispatch:       # Allow manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Clone claude-code repository
        run: git clone https://github.com/anthropics/claude-code.git

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: claude-code/.devcontainer
          push: true
          tags: ghcr.io/joesarre/claude-code-action/claude-code-sandbox:latest